---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: software-local-test
    image: ubuntu:24.04
    pre_build_image: true
    command: /bin/bash -c "sleep infinity"
    tmpfs:
      - /run

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/../
  config_options:
    defaults:
      ALLOW_BROKEN_CONDITIONALS: true
verifier:
  name: ansible
