---
- name: install cargo| confirm if cargo is installed
  ansible.builtin.stat:
    path: "~/.cargo/bin/cargo"
  register: cargo_exists
  ignore_errors: true
  changed_when: false

- name: install cargo| debug cargo_exists
  ansible.builtin.debug:
    var: cargo_exists

- name: install cargo| Download installer
  when: not cargo_exists.stat.exists
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: /tmp/cfleming_rs
    mode: "0700"
    force: "yes"

- name: install cargp| run installer
  when: not cargo_exists.stat.exists
  ansible.builtin.shell: /tmp/cfleming_rs -y
