---
- name: fish install
  ansible.builtin.include_tasks: install_github_release.yml
  vars:
    package_name: fish
    github_repo: fish-shell/fish-shell
    strip_v: false
    download_url: "https://github.com/fish-shell/fish-shell/releases/download/{{ latest_version }}/fish-{{ latest_version }}-linux-x86_64.tar.xz"
    download_dest: /tmp/fish.tar.xz
    version_cmd: "~/bin/fish --version | cut -d ' ' -f 3"
