---
- name: starship install
  ansible.builtin.include_tasks: install_github_release.yml
  vars:
    package_name: starship
    github_repo: starship/starship
    download_url: "https://github.com/starship/starship/releases/download/v{{ latest_version }}/starship-x86_64-unknown-linux-musl.tar.gz"
